export enum SagaStatus {
  STARTED = 'STARTED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  AWAITING_SHIPMENT = 'AWAITING_SHIPMENT',
  COMPLETED = 'COMPLETED',
  COMPENSATING = 'COMPENSATING',
  CANCELLED = 'CANCELLED',
}
